-- Doctrine Migration File Generated on 2021-02-18 02:37:14

-- Version DoctrineMigrations\Version20210218023457
CREATE TABLE bien (id INT AUTO_INCREMENT NOT NULL, programme_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, surface DOUBLE PRECISION NOT NULL, prix INT NOT NULL, disponible INT NOT NULL, INDEX IDX_45EDC38662BB7AEE (programme_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE lot (id INT AUTO_INCREMENT NOT NULL, bien_id INT DEFAULT NULL, lot VARCHAR(255) NOT NULL, surface DOUBLE PRECISION NOT NULL, etage VARCHAR(255) NOT NULL, orientation VARCHAR(255) NOT NULL, exterieur VARCHAR(255) NOT NULL, parking INT DEFAULT NULL, buyfor VARCHAR(255) NOT NULL, price INT DEFAULT NULL, nbpiece INT NOT NULL, INDEX IDX_B81291BBD95B80F (bien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, snippet VARCHAR(255) NOT NULL, title_tag VARCHAR(255) DEFAULT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, miniature VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE user_entity (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_6B7A5F55E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE bien ADD CONSTRAINT FK_45EDC38662BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id);
ALTER TABLE lot ADD CONSTRAINT FK_B81291BBD95B80F FOREIGN KEY (bien_id) REFERENCES bien (id);
