<?php

namespace ContainerNWGLOzT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X7xZQBxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x7xZQBx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x7xZQBx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', '.errored.WJstA1r', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::rendezVous()": the $mailer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Mailer\\MailerInterface".'],
        ], [
            'mailer' => '?',
        ]);
    }
}
