<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQRayaiK\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQRayaiK/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQRayaiK.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQRayaiK\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQRayaiK\App_KernelProdContainer([
    'container.build_hash' => 'QRayaiK',
    'container.build_id' => '6ef4496b',
    'container.build_time' => 1610098462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQRayaiK');
