<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFf338B5\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFf338B5/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFf338B5.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFf338B5\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFf338B5\App_KernelProdContainer([
    'container.build_hash' => 'Ff338B5',
    'container.build_id' => 'bf2af0e3',
    'container.build_time' => 1610104677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFf338B5');
