<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSI7Majg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSI7Majg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSI7Majg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSI7Majg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSI7Majg\App_KernelProdContainer([
    'container.build_hash' => 'SI7Majg',
    'container.build_id' => 'c11c9bdc',
    'container.build_time' => 1610101814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSI7Majg');
