<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'app_new_page' => [[], ['_controller' => 'App\\Controller\\PageController::new'], [], [['text', '/page/new']], [], []],
    'page' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/page']], [], []],
    'app_page_deletepage' => [['id'], ['_controller' => 'App\\Controller\\PageController::deletePage'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/page']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
