<?php

namespace Container1bqu2JS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JjnmH8OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JjnmH8O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JjnmH8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.TG062rZ', NULL, 'Cannot determine controller argument for "App\\Controller\\NewsController::createArticle()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'request' => '?',
            'slugger' => '?',
        ]);
    }
}
