<?php

namespace Container1bqu2JS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProspectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zvIpLOp.App\Entity\Prospect' shared service.
     *
     * @return \App\Entity\Prospect
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zvIpLOp": it references class "App\\Entity\\Prospect" but no such service exists.');
    }
}
