<?php

namespace ContainerFf338B5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PageFormType' shared autowired service.
     *
     * @return \App\Form\PageFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PageFormType'] = new \App\Form\PageFormType();
    }
}
