<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnL44w8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnL44w8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWnL44w8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWnL44w8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWnL44w8\App_KernelDevDebugContainer([
    'container.build_hash' => 'WnL44w8',
    'container.build_id' => '009eaad7',
    'container.build_time' => 1611653643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnL44w8');
