<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSecsri\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSecsri/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCSecsri.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCSecsri\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCSecsri\App_KernelDevDebugContainer([
    'container.build_hash' => 'CSecsri',
    'container.build_id' => '41098a2d',
    'container.build_time' => 1613614389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSecsri');
