<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDtjGOo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDtjGOo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDtjGOo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDtjGOo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCDtjGOo\App_KernelDevDebugContainer([
    'container.build_hash' => 'CDtjGOo',
    'container.build_id' => 'f970a3c7',
    'container.build_time' => 1611748386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDtjGOo');
